// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwVZzwWVslFNaTn2p-qfWHosdqoptXsVA',
    appId: '1:728375804780:web:171631a77b5127c71f6949',
    messagingSenderId: '728375804780',
    projectId: 'tezemlakapp',
    authDomain: 'tezemlakapp.firebaseapp.com',
    storageBucket: 'tezemlakapp.firebasestorage.app',
    measurementId: 'G-EN4K3N3T80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGydhIvaw_JJX46SuoWKmXpxpImIA_uc',
    appId: '1:728375804780:android:6b40b50351f6214c1f6949',
    messagingSenderId: '728375804780',
    projectId: 'tezemlakapp',
    storageBucket: 'tezemlakapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTdHhIVBxGateVCYEzXBLtTzkOeGj3vY',
    appId: '1:728375804780:ios:d711b0bb543e813d1f6949',
    messagingSenderId: '728375804780',
    projectId: 'tezemlakapp',
    storageBucket: 'tezemlakapp.firebasestorage.app',
    iosBundleId: 'com.example.tez2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeTdHhIVBxGateVCYEzXBLtTzkOeGj3vY',
    appId: '1:728375804780:ios:d711b0bb543e813d1f6949',
    messagingSenderId: '728375804780',
    projectId: 'tezemlakapp',
    storageBucket: 'tezemlakapp.firebasestorage.app',
    iosBundleId: 'com.example.tez2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwVZzwWVslFNaTn2p-qfWHosdqoptXsVA',
    appId: '1:728375804780:web:2387a86b33957b331f6949',
    messagingSenderId: '728375804780',
    projectId: 'tezemlakapp',
    authDomain: 'tezemlakapp.firebaseapp.com',
    storageBucket: 'tezemlakapp.firebasestorage.app',
    measurementId: 'G-ZEJK6NL4CC',
  );
}
